#!/usr/bin/env python3
"""gear.py: the party's possessions, money and shopping, as deterministic code.

Everything the party owns lives in campaigns/<c>/players/inventory.json, by container: each
character, the party stash, other places (a packhorse, a cache). Items are references to item
files (library/<system>/items/<slug>.json, or the campaign's own in dm/items/), with a count and
modifiers (masterwork, +1…+5, size, broken, charges). Prices, sale values and weights follow the
rules in library/pf1e/rules/equipment-economy.md: buying at the shop's price, selling at half
(trade goods, gems and art at full; wands by their charges left; broken items at 75%), up to the
settlement's purchase limit per item. Every change logs itself to the live session log and
rewrites the generated gear sections of the sheets and party.md.

Usage: python3 scripts/gear.py -c CAMPAIGN COMMAND [args]

  init [--where "a chest in the Arcaneum"]
                           create inventory.json: the party stash and one container per character
                           sheet, and add the generated-gear markers to the sheets and party.md
  container KEY --label "…" --kind character|stash|other [--sheet players/characters/x.md] [--where "…"]
                           a new container: a new character, a packhorse, a hidden cache
  show [CONTAINER]         what a container (or everyone) holds: items, coins, weight and load
  add CONTAINER ITEM [--qty N] [--mw] [--plus N] [--size small] [--name "…"] [--note "…"]
       [--charges N] [--equipped] [--why "…"]
                           the party gains an item (loot, a gift, found)
  remove CONTAINER ITEM [--qty N] --why "…"
                           an item is lost, destroyed or given away
  move WHAT --from A --to B [--qty N]
                           an item, or money ("25 gp"), changes hands
  equip CONTAINER ITEM / unequip CONTAINER ITEM
  use CONTAINER ITEM [--charges N]
                           a consumable is used up (one piece), or a charged item spends charges
  pay CONTAINER AMOUNT --why "…" [--to CONTAINER]
                           money leaves the party (a service, a bribe, a toll) or goes to another container
  receive CONTAINER AMOUNT --why "…"
                           money comes in (a reward, a bounty, coins found)
  price ITEM [--mw] [--plus N] [--size small] [--qty N]
                           what it costs and what it sells for
  shop SHOP                a shop's stock with prices (DM view)
  buy SHOP ITEM --by CONTAINER [--to CONTAINER] [--qty N] [--price GP --why "…"]
                           buy from a shop's stock: the buyer pays, the item goes to --to (default the buyer)
  sell SHOP CONTAINER ITEM [--qty N] [--price GP --why "…"]
                           sell to a shop: half price (full for trade goods), up to its purchase limit
  render                   rewrite the generated gear sections (after a hand fix of inventory.json)
  check                    validate inventory.json, the items it uses, and the shops

Amounts: "25 gp", "12 gp 5 sp", "3.5 gp", "40 cp". ITEM: a slug, a name, or part of one.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import combat_rules as R  # noqa: E402

PROJECT = Path(__file__).resolve().parents[1]
Inv = dict[str, Any]
Entry = dict[str, Any]
COIN_CP = {"pp": 1000, "gp": 100, "sp": 10, "cp": 1}
COINS_PER_LB = 50
MARK_BEGIN, MARK_END = "<!-- gear:begin (generated by scripts/gear.py: don't edit by hand) -->", "<!-- gear:end -->"
MODS = ("masterwork", "enhancement", "size", "broken")


class GearError(ValueError):
    """A gear command that can't run (unknown item, not enough money, not in stock, …)."""
    pass


# ---------- campaign, items, schemas ----------

def camp_dir(camp: str) -> Path:
    d = PROJECT / "campaigns" / camp
    if not (d / "campaign.md").exists():
        raise GearError(f"no campaign '{camp}'")
    return d


def system_of(camp: str) -> str:
    m = re.search(r"\*\*System:\*\*\s*([a-z0-9]+)", (camp_dir(camp) / "campaign.md").read_text(encoding="utf-8"))
    return m.group(1) if m else "pf1e"


def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower().replace("'", "")).strip("-")


def _schema(system: str, name: str) -> dict[str, Any]:
    return json.loads((PROJECT / "library" / system / f"{name}.schema.json").read_text(encoding="utf-8"))


def item_dirs(camp: str) -> list[Path]:
    """Where item files are looked up: the campaign's own first, then the system library."""
    return [camp_dir(camp) / "dm" / "items", PROJECT / "library" / system_of(camp) / "items"]


def load_item(camp: str, slug: str) -> dict[str, Any]:
    """An item file by slug, validated."""
    for d in item_dirs(camp):
        p = d / f"{slug}.json"
        if p.exists():
            data = json.loads(p.read_text(encoding="utf-8"))
            errs = R._validate(data, _schema(system_of(camp), "item"), slug, [])
            if errs:
                raise GearError(f"item file {p.relative_to(PROJECT)} has errors: " + "; ".join(errs[:4]))
            return data
    raise GearError(f"no item '{slug}': add library/{system_of(camp)}/items/{slug}.json (format: item.schema.json; "
                    f"the dm-researcher looks items up) or campaigns/{camp}/dm/items/{slug}.json for one of the campaign's own")


def find_item(camp: str, query: str) -> str:
    """An item's slug from a slug, a name or a unique part of one."""
    want = slugify(query)
    files = {p.stem: p for d in reversed(item_dirs(camp)) if d.exists() for p in d.glob("*.json")}
    if want in files:
        return want
    names = {}
    for slug, p in files.items():
        try:
            names[slug] = str(json.loads(p.read_text(encoding="utf-8")).get("name", slug)).lower()
        except ValueError:
            continue
    exact = [s for s, n in names.items() if n == query.lower()]
    hits = exact or [s for s, n in names.items() if want in s or query.lower() in n]
    if len(hits) == 1:
        return hits[0]
    if hits:
        raise GearError(f"'{query}' matches several items: {', '.join(sorted(hits)[:8])}")
    raise GearError(f"no item '{query}' in the item library (library/{system_of(camp)}/items/ or dm/items/)")


# ---------- money ----------

def parse_amount(text: str) -> int:
    """'25 gp', '12 gp 5 sp', '3.5 gp', '40cp' → copper pieces."""
    parts = re.findall(r"(\d+(?:\.\d+)?)\s*(pp|gp|sp|cp)\b", text.lower())
    rest = re.sub(r"(\d+(?:\.\d+)?)\s*(pp|gp|sp|cp)\b", "", text.lower()).strip(" ,+and")
    if not parts or rest:
        raise GearError(f"can't read the amount '{text}' (e.g. \"25 gp\", \"12 gp 5 sp\", \"3.5 gp\")")
    return round(sum(float(n) * COIN_CP[c] for n, c in parts))


def coins_cp(coins: dict[str, int]) -> int:
    return sum(coins.get(c, 0) * v for c, v in COIN_CP.items())


def fmt_cp(cp: int) -> str:
    """Copper as gp/sp/cp text: 1234 → '12 gp 3 sp 4 cp'."""
    if cp == 0:
        return "0 gp"
    gp, rest = divmod(cp, 100)
    sp, c = divmod(rest, 10)
    return " ".join(f"{n} {u}" for n, u in ((gp, "gp"), (sp, "sp"), (c, "cp")) if n)


def fmt_coins(coins: dict[str, int]) -> str:
    shown = [f"{coins[c]} {c}" for c in COIN_CP if coins.get(c)]
    return ", ".join(shown) if shown else "no coins"


def set_cp(coins: dict[str, int], total: int) -> None:
    """Re-express a purse as `total` copper, keeping its platinum where it can and making change in gp/sp/cp."""
    pp = min(coins.get("pp", 0), total // 1000)
    rest = total - pp * 1000
    gp, rest = divmod(rest, 100)
    sp, cp = divmod(rest, 10)
    coins.clear()
    coins.update({k: v for k, v in (("pp", pp), ("gp", gp), ("sp", sp), ("cp", cp)) if v})


def take_money(c: dict[str, Any], cp: int, why: str) -> None:
    have = coins_cp(c["coins"])
    if have < cp:
        raise GearError(f"{c['label']} has only {fmt_cp(have)} ({fmt_coins(c['coins'])}), not {fmt_cp(cp)} for {why}")
    set_cp(c["coins"], have - cp)


def give_money(c: dict[str, Any], cp: int) -> None:
    set_cp(c["coins"], coins_cp(c["coins"]) + cp)


# ---------- prices and weights (library/pf1e/rules/equipment-economy.md) ----------

def unit_price_cp(item: dict[str, Any], e: Entry) -> int:
    """One piece's full price, with masterwork, enhancement and size."""
    unit = item.get("unit", 1)
    cp = item["price"] * 100 / unit
    cat = item["category"]
    if cat in ("weapon", "armor", "shield") and e.get("size") == "large":
        cp *= 2
    plus = e.get("enhancement") or 0
    if e.get("masterwork") or plus:   # magic needs masterwork, and includes its cost
        cp += {"weapon": 30000, "armor": 15000, "shield": 15000, "ammunition": 600}.get(cat, 0)
    if plus:
        cp += {"weapon": plus * plus * 200000, "armor": plus * plus * 100000, "shield": plus * plus * 100000,
               "ammunition": plus * plus * 200000 / 50}.get(cat, 0)   # magic ammunition: priced per 50
    return round(cp)


def sale_value_cp(item: dict[str, Any], e: Entry, qty: int = 1) -> int:
    """What `qty` pieces sell for: half the price (full for trade goods, gems and art), prorated by the
    charges left, 75% when broken; rounded down once for the lot (20 arrows: 5 sp, not 20 × 2 cp)."""
    value: float = unit_price_cp(item, e)
    if item.get("charges") and e.get("charges") is not None:
        value = value * e["charges"] / item["charges"]
    if e.get("broken"):
        value *= 0.75
    if not item.get("sells_full") and item["category"] not in ("trade-good", "gem", "art"):
        value /= 2
    return int(value * qty + 1e-9)


def unit_weight(item: dict[str, Any], e: Entry) -> float:
    w = item["weight"] / item.get("unit", 1)
    if item["category"] in ("weapon", "armor", "shield", "ammunition"):
        w *= {"small": 0.5, "large": 2}.get(e.get("size") or "medium", 1)
    return w


HEAVY = {11: 115, 12: 130, 13: 150, 14: 175, 15: 200, 16: 230, 17: 260, 18: 300, 19: 350, 20: 400}


def heavy_load(strength: int, size: str = "medium") -> int:
    """The heavy-load maximum in lbs for a biped (CRB Table 7-4, equipment-economy.md section 5)."""
    def biped(s: int) -> int:   # Str 21+: four times the row ten lower
        return 10 * s if s <= 10 else HEAVY[s] if s <= 20 else 4 * biped(s - 10)
    return int(biped(strength) * {"small": 0.75, "medium": 1, "large": 2}.get(size, 1))


def load_of(weight: float, strength: int, size: str = "medium") -> str:
    heavy = heavy_load(strength, size)
    if weight <= heavy // 3:
        return "light"
    if weight <= 2 * heavy // 3:
        return "medium"
    if weight <= heavy:
        return "heavy"
    return "overloaded"


# ---------- inventory ----------

def inv_path(camp: str) -> Path:
    return camp_dir(camp) / "players" / "inventory.json"


def load_inv(camp: str) -> Inv:
    p = inv_path(camp)
    if not p.exists():
        raise GearError(f"no inventory yet: run `gear.py -c {camp} init` (it creates players/inventory.json)")
    return json.loads(p.read_text(encoding="utf-8"))


def save_inv(camp: str, inv: Inv) -> None:
    errs = R._validate(inv, _schema(system_of(camp), "inventory"), "inventory", [])
    if errs:
        raise GearError("the inventory would be invalid: " + "; ".join(errs[:4]))
    inv_path(camp).write_text(json.dumps(inv, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")


def container(inv: Inv, query: str) -> tuple[str, dict[str, Any]]:
    """A container by key, label, or a unique part of one ('stash', 'ilvan')."""
    cs = inv["containers"]
    q = query.lower()
    if q in cs:
        return q, cs[q]
    hits = [k for k, c in cs.items() if q in k or q in c["label"].lower()]
    if len(hits) == 1:
        return hits[0], cs[hits[0]]
    raise GearError(f"{'several containers match' if hits else 'no container'} '{query}' (containers: "
                    + ", ".join(f"{k} ({c['label']})" for k, c in cs.items()) + ")")


def entry_label(camp: str, e: Entry, qty: int | None = None) -> str:
    """'+1 longsword', 'masterwork dagger "Rasa Skinner's dagger"', '20 arrows'."""
    item = load_item(camp, e["item"])
    base = item["name"]
    mods = []
    if e.get("enhancement"):
        mods.append(f"+{e['enhancement']}")
    elif e.get("masterwork"):
        mods.append("masterwork")
    if e.get("size") and e["size"] != "medium":
        mods.append(e["size"].capitalize())
    if e.get("broken"):
        mods.append("broken")
    text = " ".join(mods + [base])
    if e.get("name"):
        text = f"{e['name']} ({text})"
    n = e["qty"] if qty is None else qty
    if n != 1:
        text = f"{n} × {text}"
    if e.get("charges") is not None:
        text += f", {e['charges']} charges"
    return text


def find_entry(camp: str, c: dict[str, Any], query: str) -> Entry:
    """An item a container holds, by slug, name, its own name, or a unique part."""
    q = query.lower()
    def keys(e: Entry) -> list[str]:
        return [e["item"], (e.get("name") or "").lower(), entry_label(camp, e, 1).lower(), load_item(camp, e["item"])["name"].lower()]
    named = [e for e in c["items"] if q in ((e.get("name") or "").lower(), entry_label(camp, e, 1).lower())]
    exact = named or [e for e in c["items"] if any(q == k for k in keys(e)) or slugify(query) == e["item"]]
    hits = exact or [e for e in c["items"] if any(q in k for k in keys(e) if k)]
    if len(hits) == 1:
        return hits[0]
    if hits:
        raise GearError(f"'{query}' matches several of {c['label']}'s items: " + "; ".join(entry_label(camp, e) for e in hits))
    raise GearError(f"{c['label']} has no '{query}' (holds: " + ("; ".join(entry_label(camp, e) for e in c["items"]) or "nothing") + ")")


def same_kind(a: Entry, b: Entry) -> bool:
    """Whether two entries can share a stack: the same item, modifiers, name and note, neither equipped."""
    return all(a.get(k) == b.get(k) for k in ("item", "name", "note", "charges") + MODS) and not a.get("equipped") and not b.get("equipped")


def put(c: dict[str, Any], e: Entry) -> None:
    """Add an entry to a container, stacking with an identical one."""
    for x in c["items"]:
        if same_kind(x, e):
            x["qty"] += e["qty"]
            return
    c["items"].append(e)


def take(c: dict[str, Any], e: Entry, qty: int) -> Entry:
    """Remove `qty` pieces of an entry; returns the removed part as its own entry."""
    if qty > e["qty"]:
        raise GearError(f"{c['label']} has only {e['qty']}, not {qty}")
    part = {k: v for k, v in e.items() if k != "equipped"}
    part["qty"] = qty
    e["qty"] -= qty
    if e["qty"] == 0:
        c["items"].remove(e)
    return part


def new_entry(slug: str, args: argparse.Namespace) -> Entry:
    e: Entry = {"item": slug, "qty": getattr(args, "qty", None) or 1}
    if getattr(args, "mw", False):
        e["masterwork"] = True
    if getattr(args, "plus", None):
        e["enhancement"] = args.plus
        e["masterwork"] = True
    if getattr(args, "size", None) and args.size != "medium":
        e["size"] = args.size
    for k in ("name", "note", "charges"):
        if getattr(args, k, None) is not None:
            e[k] = getattr(args, k)
    if getattr(args, "equipped", False):
        e["equipped"] = True
    return e


def sheet_profile(camp: str, c: dict[str, Any]) -> dict[str, Any]:
    """The combat profile of a character container's sheet (for Str and size), or {}."""
    if not c.get("sheet"):
        return {}
    p = camp_dir(camp) / c["sheet"]
    if not p.exists():
        return {}
    blocks = R.profile_text_blocks(p.read_text(encoding="utf-8"))
    try:
        return json.loads(blocks[0]) if blocks else {}
    except ValueError:
        return {}


def weight_of(camp: str, c: dict[str, Any]) -> float:
    items = sum(unit_weight(load_item(camp, e["item"]), e) * e["qty"] for e in c["items"])
    return items + sum(c["coins"].values()) / COINS_PER_LB


def describe(camp: str, key: str, c: dict[str, Any], dm: bool = True) -> list[str]:
    """A container's contents, coins, weight and (for characters) load."""
    head = f"{c['label']}" + (f" — {c['where']}" if c.get("where") else "")
    out = [head + (f" [{key}]" if dm else "")]
    for e in c["items"]:
        out.append(f"  - {entry_label(camp, e)}" + (" (equipped)" if e.get("equipped") else "") + (f" — {e['note']}" if e.get("note") else ""))
    if not c["items"]:
        out.append("  - (nothing)")
    w = weight_of(camp, c)
    line = f"  Coins: {fmt_coins(c['coins'])} · Weight: {w:.1f} lbs"
    if c["kind"] == "character":
        prof = sheet_profile(camp, c)
        strength = c.get("str") or prof.get("str")
        size = c.get("size") or {1: "medium"}.get(prof.get("size", 1), "medium")
        if strength:
            heavy = heavy_load(int(strength), size)
            line += f" · Load: {load_of(w, int(strength), size)} (Str {strength}: light ≤ {heavy // 3}, medium ≤ {2 * heavy // 3}, heavy ≤ {heavy})"
    out.append(line)
    return out


# ---------- the live log and the generated sections ----------

def live_log(camp: str) -> Path | None:
    m = re.search(r"\*\*Sessions played:\*\*\s*(\d+)", (camp_dir(camp) / "campaign.md").read_text(encoding="utf-8"))
    nn = (int(m.group(1)) if m else 0) + 1
    p = camp_dir(camp) / "dm" / "session-log" / f"session-{nn:02d}.md"
    return p if p.exists() else None


def log(camp: str, line: str) -> None:
    """Append a line to the live log's "Gear & money" section (created before "## Changes" if missing)."""
    p = live_log(camp)
    if not p:
        return
    text = p.read_text(encoding="utf-8")
    m = re.search(r"^## Gear & money[^\n]*\n(.*?)(?=^## |\Z)", text, re.S | re.M)
    if m:
        body = m.group(1).rstrip("\n")
        text = text[:m.start(1)] + body + f"\n- {line}\n\n" + text[m.end(1):]
    else:
        section = f"## Gear & money\nWritten by the `gear` tool.\n- {line}\n\n"
        i = text.find("\n## Changes")
        text = (text[:i + 1] + section + text[i + 1:]) if i >= 0 else text.rstrip("\n") + "\n\n" + section
    p.write_text(text, encoding="utf-8")


def replace_marked(text: str, body: str) -> str | None:
    i, j = text.find(MARK_BEGIN), text.find(MARK_END)
    if i < 0 or j < i:
        return None
    return text[:i + len(MARK_BEGIN)] + "\n" + body.rstrip("\n") + "\n" + text[j:]


def render(camp: str, inv: Inv) -> list[str]:
    """Rewrite the generated gear sections: each character sheet's, and the stash's in party.md."""
    notes = []
    for key, c in inv["containers"].items():
        if c["kind"] == "character" and c.get("sheet"):
            p = camp_dir(camp) / c["sheet"]
        elif c["kind"] != "character":
            p = camp_dir(camp) / "players" / "party.md"
        else:
            continue
        if not p.exists():
            continue
        text = p.read_text(encoding="utf-8")
        if c["kind"] == "character":
            body = "\n".join(describe(camp, key, c, dm=False)[1:])
            new = replace_marked(text, body)
        else:   # all non-character containers share party.md's block
            others = [(k, x) for k, x in inv["containers"].items() if x["kind"] != "character"]
            if others[0][0] != key:
                continue
            body = "\n\n".join("\n".join(describe(camp, k, x, dm=False)) for k, x in others)
            new = replace_marked(text, body)
        if new is None:
            notes.append(f"no gear markers in {p.relative_to(PROJECT)}: run init, or add {MARK_BEGIN} … {MARK_END}")
        elif new != text:
            p.write_text(new, encoding="utf-8")
    return notes


def add_markers(path: Path, heading: str) -> bool:
    """Put the generated-gear markers right under `heading` (created at the end if missing). Existing
    prose stays below them."""
    if not path.exists():
        return False
    text = path.read_text(encoding="utf-8")
    if MARK_BEGIN in text:
        return False
    block = f"{MARK_BEGIN}\n{MARK_END}\n"
    m = re.search(rf"^{re.escape(heading)}[^\n]*\n", text, re.M)
    if m:
        text = text[:m.end()] + block + text[m.end():]
    else:
        text = text.rstrip("\n") + f"\n\n{heading}\n{block}"
    path.write_text(text, encoding="utf-8")
    return True


# ---------- shops ----------

def shop_path(camp: str, query: str) -> Path:
    d = camp_dir(camp) / "dm" / "shops"
    files = sorted(d.glob("*.json")) if d.exists() else []
    want = slugify(query)
    for p in files:
        if p.stem == want:
            return p
    hits = [p for p in files if want in p.stem or query.lower() in str(json.loads(p.read_text(encoding="utf-8")).get("name", "")).lower()]
    if len(hits) == 1:
        return hits[0]
    raise GearError(f"{'several shops match' if hits else 'no shop'} '{query}' in dm/shops/ (shops: "
                    + (", ".join(p.stem for p in files) or "none yet: write one, format library/<system>/shop.schema.json") + ")")


def load_shop(camp: str, query: str) -> tuple[Path, dict[str, Any]]:
    p = shop_path(camp, query)
    data = json.loads(p.read_text(encoding="utf-8"))
    errs = R._validate(data, _schema(system_of(camp), "shop"), p.stem, [])
    if errs:
        raise GearError(f"shop file {p.relative_to(PROJECT)} has errors: " + "; ".join(errs[:4]))
    return p, data


def stock_price_cp(camp: str, shop: dict[str, Any], s: Entry) -> int:
    if s.get("price") is not None:
        return round(s["price"] * 100)
    return round(unit_price_cp(load_item(camp, s["item"]), s) * shop.get("markup", 1))


def find_stock(camp: str, shop: dict[str, Any], query: str) -> Entry:
    q = query.lower()
    def label(s: Entry) -> str:
        return entry_label(camp, dict(s, qty=1)).lower()
    named = [s for s in shop["stock"] if label(s) == q]   # "longsword" is the plain one, not the masterwork one
    exact = named or [s for s in shop["stock"] if s["item"] == slugify(query)]
    hits = exact or [s for s in shop["stock"] if q in label(s) or slugify(query) in s["item"]]
    if len(hits) == 1:
        return hits[0]
    raise GearError(f"{shop['name']} {'has several' if hits else 'has no'} '{query}' (stock: "
                    + "; ".join(label(s) for s in shop["stock"]) + ")")


def buys(camp: str, shop: dict[str, Any], item: dict[str, Any]) -> bool:
    b = shop.get("buys")
    if b == "all":
        return True
    if b == "none":
        return False
    cats = b if isinstance(b, list) else {load_item(camp, s["item"])["category"] for s in shop["stock"]}
    return item["category"] in cats


# ---------- commands ----------

def cmd_init(camp: str, args: argparse.Namespace) -> str:
    if inv_path(camp).exists():
        raise GearError("players/inventory.json exists already")
    inv: Inv = {"containers": {"stash": {"label": "Party stash", "kind": "stash", "coins": {}, "items": []}}}
    if args.where:
        inv["containers"]["stash"]["where"] = args.where
    out = []
    for p in sorted((camp_dir(camp) / "players" / "characters").glob("*.md")):
        if p.name.lower() == "readme.md":
            continue
        m = re.search(r"^#\s+(.+)$", p.read_text(encoding="utf-8"), re.M)
        label = (m.group(1).strip() if m else p.stem).split("—")[0].split(" - ")[0].strip()
        inv["containers"][p.stem] = {"label": label, "kind": "character", "sheet": f"players/characters/{p.name}",
                                     "coins": {}, "items": []}
        if add_markers(p, "## Gear"):
            out.append(f"  markers added under ## Gear in {p.name}")
    if add_markers(camp_dir(camp) / "players" / "party.md", "## Gold & shared loot"):
        out.append("  markers added in party.md")
    save_inv(camp, inv)
    render(camp, inv)
    return "\n".join([f"inventory created with containers: {', '.join(inv['containers'])}"] + out)


def cmd_container(camp: str, args: argparse.Namespace) -> str:
    inv = load_inv(camp)
    key = slugify(args.key)
    if key in inv["containers"]:
        raise GearError(f"a container '{key}' exists already")
    c: dict[str, Any] = {"label": args.label, "kind": args.kind, "coins": {}, "items": []}
    if args.sheet:
        if not (camp_dir(camp) / args.sheet).exists():
            raise GearError(f"no sheet {args.sheet} in the campaign")
        c["sheet"] = args.sheet
        add_markers(camp_dir(camp) / args.sheet, "## Gear")
    if args.where:
        c["where"] = args.where
    inv["containers"][key] = c
    save_inv(camp, inv)
    log(camp, f"new container: {args.label}" + (f" ({args.where})" if args.where else ""))
    render(camp, inv)
    return f"container '{key}' ({args.label}) added"


def cmd_show(camp: str, args: argparse.Namespace) -> str:
    inv = load_inv(camp)
    if args.container:
        key, c = container(inv, args.container)
        return "\n".join(describe(camp, key, c))
    return "\n\n".join("\n".join(describe(camp, k, c)) for k, c in inv["containers"].items())


def cmd_price(camp: str, args: argparse.Namespace) -> str:
    slug = find_item(camp, args.item)
    item = load_item(camp, slug)
    e = new_entry(slug, args)
    n = e["qty"]
    return (f"{entry_label(camp, e)}: costs {fmt_cp(unit_price_cp(item, e) * n)}, sells for {fmt_cp(sale_value_cp(item, e, n))}"
            + f" · {unit_weight(item, e) * n:g} lbs")


def mutate(camp: str, args: argparse.Namespace) -> str:
    """The commands that change something: they log themselves and re-render the sheets."""
    inv = load_inv(camp)
    cmd = args.command
    why = f" ({args.why})" if getattr(args, "why", None) else ""
    if cmd == "add":
        key, c = container(inv, args.container)
        slug = find_item(camp, args.item)
        e = new_entry(slug, args)
        put(c, e)
        msg = f"{c['label']} gains {entry_label(camp, e)}{why}"
    elif cmd == "remove":
        key, c = container(inv, args.container)
        e = find_entry(camp, c, args.item)
        part = take(c, e, args.qty or e["qty"])
        msg = f"{c['label']} loses {entry_label(camp, part)}{why}"
    elif cmd == "move":
        _ka, a = container(inv, args.frm)
        _kb, b = container(inv, args.to)
        try:
            cp = parse_amount(args.what)
        except GearError:
            cp = None
        if cp is not None:
            take_money(a, cp, f"moving it to {b['label']}")
            give_money(b, cp)
            msg = f"{fmt_cp(cp)} moves from {a['label']} to {b['label']}"
        else:
            e = find_entry(camp, a, args.what)
            part = take(a, e, args.qty or e["qty"])
            put(b, part)
            msg = f"{entry_label(camp, part)} moves from {a['label']} to {b['label']}"
    elif cmd in ("equip", "unequip"):
        key, c = container(inv, args.container)
        e = find_entry(camp, c, args.item)
        if cmd == "equip" and e["qty"] > 1:   # one piece is worn or wielded, the rest stays packed
            part = take(c, e, 1)
            part["equipped"] = True
            c["items"].append(part)
            e = part
        elif cmd == "equip":
            e["equipped"] = True
        else:
            e.pop("equipped", None)
            c["items"].remove(e)
            put(c, e)
        msg = f"{c['label']} {'equips' if cmd == 'equip' else 'puts away'} {entry_label(camp, e, 1)}"
    elif cmd == "use":
        key, c = container(inv, args.container)
        e = find_entry(camp, c, args.item)
        item = load_item(camp, e["item"])
        if item.get("charges"):
            n = args.charges or 1
            left = e.get("charges", item["charges"])
            if n > left:
                raise GearError(f"{entry_label(camp, e, 1)} has only {left} charges left")
            e["charges"] = left - n
            msg = f"{c['label']} uses {n} charge(s) of {entry_label(camp, e, 1)}"
        elif item.get("consumable") or item["category"] in ("potion", "oil", "scroll", "alchemical", "ammunition"):
            part = take(c, e, 1)
            msg = f"{c['label']} uses up {entry_label(camp, part)}"
        else:
            raise GearError(f"{item['name']} isn't used up by using it (not a consumable or charged item)")
    elif cmd == "pay":
        key, c = container(inv, args.container)
        cp = parse_amount(args.amount)
        if args.to:
            _kt, t = container(inv, args.to)
            take_money(c, cp, args.why or "the payment")
            give_money(t, cp)
            msg = f"{c['label']} pays {fmt_cp(cp)} to {t['label']}{why}"
        else:
            if not args.why:
                raise GearError("say what the money is for: --why \"…\"")
            take_money(c, cp, args.why)
            msg = f"{c['label']} pays {fmt_cp(cp)}{why}"
    elif cmd == "receive":
        key, c = container(inv, args.container)
        if not args.why:
            raise GearError("say where the money comes from: --why \"…\"")
        cp = parse_amount(args.amount)
        give_money(c, cp)
        msg = f"{c['label']} receives {fmt_cp(cp)}{why}"
    elif cmd == "buy":
        path, shop = load_shop(camp, args.shop)
        s = find_stock(camp, shop, args.item)
        qty = args.qty or 1
        if s.get("qty") is not None and s["qty"] < qty:
            raise GearError(f"{shop['name']} has only {s['qty']} of that in stock")
        each = round(args.price * 100) if args.price is not None else stock_price_cp(camp, shop, s)
        if args.price is not None and not args.why:
            raise GearError("a price other than the shop's needs a reason: --why \"haggled\"")
        _kb, buyer = container(inv, args.by)
        _kt, to = container(inv, args.to) if args.to else (_kb, buyer)
        take_money(buyer, each * qty, f"{qty} × {s['item']}")
        e = {k: v for k, v in s.items() if k not in ("qty", "price")}
        e["qty"] = qty
        put(to, e)
        if s.get("qty") is not None:
            s["qty"] -= qty
        path.write_text(json.dumps(shop, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        msg = (f"{buyer['label']} buys {entry_label(camp, e)} at {shop['name']} for {fmt_cp(each * qty)}"
               + (f" (to {to['label']})" if to is not buyer else "") + why)
    elif cmd == "sell":
        path, shop = load_shop(camp, args.shop)
        _ks, seller = container(inv, args.container)
        e = find_entry(camp, seller, args.item)
        item = load_item(camp, e["item"])
        if not buys(camp, shop, item):
            raise GearError(f"{shop['name']} doesn't deal in {item['category']} (buys: {shop.get('buys', 'what it stocks')})")
        qty = args.qty or e["qty"]
        each = round(args.price * 100) if args.price is not None else sale_value_cp(item, e)
        total = each * qty if args.price is not None else sale_value_cp(item, e, qty)
        if args.price is not None and not args.why:
            raise GearError("a price other than the rules' needs a reason: --why \"haggled\"")
        limit = shop.get("purchase_limit")
        if limit is not None and each > limit * 100:
            raise GearError(f"{shop['name']} pays at most {fmt_cp(round(limit * 100))} for a single item (the settlement's "
                            f"purchase limit), and this one is worth {fmt_cp(each)}: settle for less (--price {limit} "
                            f"--why \"purchase limit\"), find a bigger market, or a specific buyer")
        part = take(seller, e, qty)
        give_money(seller, total)
        stocked = next((s for s in shop["stock"] if same_kind(dict(s, qty=1), dict(part, qty=1)) and s.get("qty") is not None), None)
        if stocked:
            stocked["qty"] += qty
        path.write_text(json.dumps(shop, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        msg = f"{seller['label']} sells {entry_label(camp, part)} to {shop['name']} for {fmt_cp(total)}{why}"
    else:
        raise GearError(f"unknown command {cmd}")
    save_inv(camp, inv)
    log(camp, msg)
    notes = render(camp, inv)
    return "\n".join([msg] + [f"  {n}" for n in notes])


def cmd_shop(camp: str, args: argparse.Namespace) -> str:
    _p, shop = load_shop(camp, args.shop)
    out = [f"{shop['name']}" + (f" ({shop['settlement']})" if shop.get("settlement") else "")
           + (f" · pays at most {shop['purchase_limit']} gp per item" if shop.get("purchase_limit") is not None else "")]
    for s in shop["stock"]:
        n = "plenty" if s.get("qty") is None else str(s["qty"])
        out.append(f"  - {entry_label(camp, dict(s, qty=1))}: {fmt_cp(stock_price_cp(camp, shop, s))} each ({n} in stock)")
    if shop.get("notes"):
        out.append(f"  Notes: {shop['notes']}")
    return "\n".join(out)


def cmd_check(camp: str, args: argparse.Namespace) -> str:
    out, bad = [], 0
    if inv_path(camp).exists():
        inv = load_inv(camp)
        errs = R._validate(inv, _schema(system_of(camp), "inventory"), "inventory", [])
        for e in errs:
            out.append(f"  inventory: {e}")
        for c in inv["containers"].values():
            for e in c["items"]:
                try:
                    load_item(camp, e["item"])
                except GearError as x:
                    out.append(f"  {c['label']}: {x}")
    d = camp_dir(camp) / "dm" / "shops"
    for p in sorted(d.glob("*.json")) if d.exists() else []:
        try:
            _p, shop = load_shop(camp, p.stem)
            for s in shop["stock"]:
                load_item(camp, s["item"])
        except GearError as x:
            out.append(f"  shop {p.stem}: {x}")
    bad = len(out)
    return "\n".join(["OK" if not bad else f"{bad} problem(s):"] + out)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("-c", "--campaign", required=True)
    sub = p.add_subparsers(dest="command", required=True)

    def item_mods(sp: argparse.ArgumentParser) -> None:
        sp.add_argument("--qty", type=int); sp.add_argument("--mw", action="store_true", help="masterwork")
        sp.add_argument("--plus", type=int, choices=range(1, 6), help="enhancement bonus (includes masterwork)")
        sp.add_argument("--size", choices=["small", "medium", "large"])

    sub.add_parser("init").add_argument("--where", help="what and where the party stash is")
    sub.add_parser("show").add_argument("container", nargs="?")
    ct = sub.add_parser("container"); ct.add_argument("key"); ct.add_argument("--label", required=True)
    ct.add_argument("--kind", choices=["character", "stash", "other"], required=True)
    ct.add_argument("--sheet"); ct.add_argument("--where")
    a = sub.add_parser("add"); a.add_argument("container"); a.add_argument("item"); item_mods(a)
    a.add_argument("--name"); a.add_argument("--note"); a.add_argument("--charges", type=int)
    a.add_argument("--equipped", action="store_true"); a.add_argument("--why")
    r = sub.add_parser("remove"); r.add_argument("container"); r.add_argument("item"); r.add_argument("--qty", type=int)
    r.add_argument("--why", required=True)
    m = sub.add_parser("move"); m.add_argument("what"); m.add_argument("--from", dest="frm", required=True)
    m.add_argument("--to", required=True); m.add_argument("--qty", type=int)
    for nm in ("equip", "unequip"):
        e = sub.add_parser(nm); e.add_argument("container"); e.add_argument("item")
    u = sub.add_parser("use"); u.add_argument("container"); u.add_argument("item"); u.add_argument("--charges", type=int)
    pay = sub.add_parser("pay"); pay.add_argument("container"); pay.add_argument("amount"); pay.add_argument("--why")
    pay.add_argument("--to")
    rc = sub.add_parser("receive"); rc.add_argument("container"); rc.add_argument("amount"); rc.add_argument("--why")
    pr = sub.add_parser("price"); pr.add_argument("item"); item_mods(pr)
    sub.add_parser("shop").add_argument("shop")
    b = sub.add_parser("buy"); b.add_argument("shop"); b.add_argument("item"); b.add_argument("--by", required=True)
    b.add_argument("--to"); b.add_argument("--qty", type=int); b.add_argument("--price", type=float); b.add_argument("--why")
    s = sub.add_parser("sell"); s.add_argument("shop"); s.add_argument("container"); s.add_argument("item")
    s.add_argument("--qty", type=int); s.add_argument("--price", type=float); s.add_argument("--why")
    sub.add_parser("render"); sub.add_parser("check")
    args = p.parse_args(argv)
    try:
        if args.command in ("add", "remove", "move", "equip", "unequip", "use", "pay", "receive", "buy", "sell"):
            out = mutate(args.campaign, args)
        elif args.command == "render":
            out = "\n".join(render(args.campaign, load_inv(args.campaign))) or "rendered"
        else:
            out = {"init": cmd_init, "container": cmd_container, "show": cmd_show, "price": cmd_price, "shop": cmd_shop, "check": cmd_check}[args.command](args.campaign, args)
    except GearError as e:
        print(f"gear error: {e}", file=sys.stderr)
        return 1
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
